[2021-12-15 05:10:33,307] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: tutorial_taskflow_api_etl.load manual__2021-12-15T05:10:26.053742+00:00 [queued]>
[2021-12-15 05:10:33,315] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: tutorial_taskflow_api_etl.load manual__2021-12-15T05:10:26.053742+00:00 [queued]>
[2021-12-15 05:10:33,315] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-15 05:10:33,315] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-15 05:10:33,315] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-15 05:10:33,329] {taskinstance.py:1262} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2021-12-15 05:10:26.053742+00:00
[2021-12-15 05:10:33,332] {standard_task_runner.py:52} INFO - Started process 2534 to run task
[2021-12-15 05:10:33,335] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'tutorial_taskflow_api_etl', 'load', 'manual__2021-12-15T05:10:26.053742+00:00', '--job-id', '4', '--raw', '--subdir', '/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl.py', '--cfg-path', '/tmp/tmpez5hs1yj', '--error-file', '/tmp/tmpg2ndcz5w']
[2021-12-15 05:10:33,336] {standard_task_runner.py:77} INFO - Job 4: Subtask load
[2021-12-15 05:10:33,365] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial_taskflow_api_etl.load manual__2021-12-15T05:10:26.053742+00:00 [running]> on host 66df403e5cd0
[2021-12-15 05:10:33,393] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/xcom.py:322 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:10:33,398] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/taskinstance.py:2298 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:10:33,403] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/renderedtifields.py:126 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:10:33,411] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/renderedtifields.py:162 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2021-12-15 05:10:33,414] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/renderedtifields.py:159 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:10:33,417] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=tutorial_taskflow_api_etl
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2021-12-15T05:10:26.053742+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-15T05:10:26.053742+00:00
[2021-12-15 05:10:33,417] {logging_mixin.py:109} INFO - Total order value is: 1236.70
[2021-12-15 05:10:33,417] {python.py:152} INFO - Done. Returned value was: None
[2021-12-15 05:10:33,422] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=tutorial_taskflow_api_etl, task_id=load, execution_date=20211215T051026, start_date=20211215T051033, end_date=20211215T051033
[2021-12-15 05:10:33,470] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-15 05:10:33,488] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-15 05:10:33,490] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:1069 SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
[2021-12-15 05:10:33,491] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:1069 SADeprecationWarning: Query.values() is deprecated and will be removed in a future release.  Please use Query.with_entities() (deprecated since: 1.4)
